remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: true

# Modify the contents below for the specific project.

title: "Tile Matching"
description: "A memory game where players attempt to find matching images by flipping tiles."
author:
  name: "Marshall Levi Eldridge"

# Do not change the following line.
  copyright: true
